### ISSUE TITLE
Can not select board USB port because it keeps appearing and disappearing

### ISSUE THREAD

**Issue by Jeroen88** [arduino/help-center-content#126]
**Article summary**
See the Arduino forum discussion [here](https://forum.arduino.cc/t/ubuntu-arduino-ide-2-usb-port-not-detected/991908/14) starting at article no. 6.

**More information**
Include any/all of the following:

- For an ESP32 create a program that crashes and reboots again, over and over
- Use the buttons to put the board into upload mode, now select the serial port and upload a program that does not crash
- Not an error log but more information in the forum
- See above

**Comment by per1234** [comment]
I would not recommend making an article specifically about the ESP32 board. Instead I would suggest the addition of information [here](https://github.com/arduino/help-center-content/blob/main/content/Software%20Support/Upload/If-your-board-does-not-appear-in-the-port-menu.md) about sketch code being one potential cause of a native USB board not having a port.

This specific cause can be identified by comparing the behavior after uploading the **File > New** sketch to the board. If the problem occurs with the user's sketch, but not with a simple "known good" sketch, then something in the sketch code is causing the problem. It is helpful to provide a list of examples of things that can cause that. These would include:

- Putting the board to sleep
- Disabling interrupts
- Crashing Mbed OS

I don't think they would be appropriate for inclusion in the article, but since they might be useful to the person developing the article, I will provide some minimal examples of code that produces this state (some may only work with specific boards):

### Putting MCU to sleep

```cpp
#include <ArduinoLowPower.h>
void setup() {
  LowPower.sleep();
}
void loop() {}
```

### Disable interrupts

```cpp
void setup() {
  noInterrupts();
}
void loop() {}
```

### Divide by zero
```cpp
void setup() {
  volatile byte foo = 1 / 0;  // The variable is volatile to prevent it from being optimized out since it is unused in this minimal sketch.
}
void loop() {}
```

### Overriding initialization code in default `main` function

```cpp
// Override core's main()
int main() {
  while(true) {}
  return 0;
}
```

**Comment by seaxwi** [comment]
Thanks @per1234. I will close this issue but make note of this information.
